# Generated by Django 6.1.1 on 2026-09-28 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options_payment_payment_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(
                blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
    ]
