# Generated by Django 6.0.9 on 2026-10-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_payment_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счёт"),
                    ("stripe", "Stripe"),
                ],
                default="transfer",
                max_length=10,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
